name: Go build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Directory
      run: mkdir -p ${{ github.workspace }}/build

    - name: Build
      run: go build -o ${{ github.workspace }}/build -v ./...

    - name: Test
      run: go test -v ./...
